import type { InteldocState } from './types'
import {
  ACCESS_AUDIT_SEED,
  ACCESS_BY_DEPARTMENT_SEED,
  ACCESS_INCIDENTS_SEED,
  ADOPTION_BY_DEPARTMENT_SEED,
  ADOPTION_BY_DOCTOR_SEED,
  AUDIT_EVENTS_SEED,
  COMPLIANCE_CHECKS_SEED,
  COMPLIANCE_STATE_SEED,
  FUNNEL_SEED,
  KPI_TREND_SEED,
  PILOT_GOAL_SEED,
  PILOT_KPIS_SEED,
} from '../data/adminMockData'

/**
 * Seed state for the demo.
 * - p1 is the canonical demo patient Мария Иванова — seeded here and also
 *   (re)created by the entry flow / demo segments from the same identity.
 * - p2 / p3 / p4 populate the doctor's patient list so it doesn't render empty.
 */
export const SEED: InteldocState = {
  currentPatientId: null,
  doctorActivePatientId: null,
  currentDoctorId: 'd1',

  webAuth: null,

  hasCompletedOnboarding: false,
  accountDraft: null,
  consentDraft: null,
  accessSigned: false,

  lastSavedAt: null,

  // Patient backend public_id is captured only in BACKEND_MODE at commit.
  backendPatientPublicId: null,

  // Mocked e-sign + consent bundles for the three pre-onboarded demo
  // patients (p2 / p3 / p4). Lets Profile · «Согласия» render meaningful
  // version + signed-date info when stakeholders flip between patients via
  // the dev role switcher.
  esignRecords: [
    {
      id: 'esign-p2',
      userId: 'p2',
      documentHash: 'mock-hash-p2',
      signedAt: '2026-04-05T10:01:00Z',
      signatureMethod: 'mock_no_otp',
      recipientClinicId: 'endokor',
      partnerId: 'endokor',
    },
    {
      id: 'esign-p3',
      userId: 'p3',
      documentHash: 'mock-hash-p3',
      signedAt: '2026-04-08T09:31:00Z',
      signatureMethod: 'mock_no_otp',
      recipientClinicId: 'endokor',
      partnerId: 'endokor',
    },
    {
      id: 'esign-p4',
      userId: 'p4',
      documentHash: 'mock-hash-p4',
      signedAt: '2026-04-12T11:01:00Z',
      signatureMethod: 'mock_no_otp',
      recipientClinicId: 'endokor',
      partnerId: 'endokor',
    },
  ],
  consentBundles: [
    {
      bundleId: 'bundle-p2',
      userId: 'p2',
      capturedAt: '2026-04-05T10:02:00Z',
      ipAddress: 'browser-unknown',
      userAgent: 'seed',
      linkedEsignId: 'esign-p2',
      partnerId: 'endokor',
      consents: [
        {
          id: 'clinic_access',
          version: '2026.05.27',
          accepted: true,
          ackMechanism: 'scroll_to_end',
        },
        {
          id: 'pdn_general',
          version: '2026.04.23',
          accepted: true,
          ackMechanism: 'scroll_to_end',
        },
        {
          id: 'pdn_special',
          // intentionally older than spec's current 2026.05.12 to surface the
          // «новая версия — переподписать» banner on Profile for p2.
          version: '2026.04.23',
          accepted: true,
          ackMechanism: 'scroll_to_end',
          smsConfirmed: true,
          smsConfirmedAt: '2026-04-05T10:02:30Z',
        },
        {
          id: 'tos',
          version: '2026.05.12',
          accepted: true,
          ackMechanism: 'scroll_to_end',
        },
        {
          id: 'marketing',
          version: '2026.04.23',
          accepted: true,
          ackMechanism: 'direct_tick',
          channels: ['email', 'sms', 'push'],
        },
      ],
    },
    {
      bundleId: 'bundle-p3',
      userId: 'p3',
      capturedAt: '2026-04-08T09:32:00Z',
      ipAddress: 'browser-unknown',
      userAgent: 'seed',
      linkedEsignId: 'esign-p3',
      partnerId: 'endokor',
      consents: [
        {
          id: 'clinic_access',
          version: '2026.05.27',
          accepted: true,
          ackMechanism: 'scroll_to_end',
        },
        {
          id: 'pdn_general',
          version: '2026.04.23',
          accepted: true,
          ackMechanism: 'scroll_to_end',
        },
        {
          id: 'pdn_special',
          version: '2026.05.12',
          accepted: true,
          ackMechanism: 'scroll_to_end',
          smsConfirmed: true,
          smsConfirmedAt: '2026-04-08T09:32:30Z',
        },
        {
          id: 'tos',
          version: '2026.05.12',
          accepted: true,
          ackMechanism: 'scroll_to_end',
        },
        {
          id: 'marketing',
          version: '2026.04.23',
          accepted: true,
          ackMechanism: 'direct_tick',
          channels: ['email', 'sms', 'push'],
        },
      ],
    },
    {
      bundleId: 'bundle-p4',
      userId: 'p4',
      capturedAt: '2026-04-12T11:02:00Z',
      ipAddress: 'browser-unknown',
      userAgent: 'seed',
      linkedEsignId: 'esign-p4',
      partnerId: 'endokor',
      consents: [
        {
          id: 'clinic_access',
          version: '2026.05.27',
          accepted: true,
          ackMechanism: 'scroll_to_end',
        },
        {
          id: 'pdn_general',
          version: '2026.04.23',
          accepted: true,
          ackMechanism: 'scroll_to_end',
        },
        {
          id: 'pdn_special',
          version: '2026.05.12',
          accepted: true,
          ackMechanism: 'scroll_to_end',
          smsConfirmed: true,
          smsConfirmedAt: '2026-04-12T11:02:30Z',
        },
        {
          id: 'tos',
          version: '2026.05.12',
          accepted: true,
          ackMechanism: 'scroll_to_end',
        },
        {
          id: 'marketing',
          version: '2026.04.23',
          accepted: true,
          ackMechanism: 'direct_tick',
          channels: ['email', 'sms', 'push'],
        },
      ],
    },
  ],

  clinics: [
    {
      id: 'endokor',
      name: 'Клиника-партнёр',
      shortName: 'Эндокор',
      department: 'Отделение диабетологии',
    },
  ],

  doctors: [
    {
      id: 'd1',
      name: 'Соколов А.В.',
      specialty: 'Эндокринолог',
      clinicId: 'endokor',
    },
  ],

  patients: [
    {
      // p1 — the canonical demo patient Мария Иванова. Also the patient-app
      // session persona (the entry flow rebuilds p1 from the onboarding draft).
      // Seeded here so the doctor queue and the A02 audit show her even when the
      // patient demo hasn't been run — she is the cross-surface revocation hero.
      id: 'p1',
      name: 'Иванова Мария Сергеевна',
      dob: '1972-02-10',
      gender: 'female',
      phone: '+7 (916) 555-12-01',
      identifiers: { oms: '7700000000000001' },
      partnerClinic: 'endokor',
      department: 'Отделение диабетологии',
      attendingDoctorId: 'd1',
      createdAt: '2026-03-18T14:20:00Z',
      diagnosis: { label: 'Диабет 2 типа', confirmed: true },
      heightCm: 165,
      weightKg: 78,
      chronicConditions: ['Гипертония 2 ст.'],
      allergies: [],
      baselineUpdatedAt: '2026-03-18T14:25:00Z',
      identityVerifiedAt: '2026-03-18T14:28:00Z',
    },
    {
      id: 'p2',
      name: 'Волков Сергей Николаевич',
      dob: '1968-03-12',
      gender: 'male',
      phone: '+7 (916) 555-12-02',
      identifiers: { oms: '7700000000000002' },
      partnerClinic: 'endokor',
      department: 'Отделение диабетологии',
      attendingDoctorId: 'd1',
      createdAt: '2026-04-05T10:00:00Z',
      prepCompletedAt: '2026-04-25T19:42:00Z',
      prepTimeSpentMin: 14,
      diagnosis: { label: 'Диабет 2 типа', confirmed: true },
      heightCm: 178,
      weightKg: 96,
      chronicConditions: ['Гипертония 2 ст.', 'Дислипидемия'],
      allergies: ['Пенициллин'],
      baselineUpdatedAt: '2026-04-05T10:05:00Z',
      identityVerifiedAt: '2026-04-05T10:08:00Z',
    },
    {
      id: 'p3',
      name: 'Михайлова Елена Викторовна',
      dob: '1975-11-02',
      gender: 'female',
      phone: '+7 (916) 555-12-03',
      identifiers: { oms: '7700000000000003' },
      partnerClinic: 'endokor',
      department: 'Отделение диабетологии',
      attendingDoctorId: 'd1',
      createdAt: '2026-04-08T09:30:00Z',
      prepCompletedAt: '2026-04-22T16:15:00Z',
      prepTimeSpentMin: 9,
      diagnosis: { label: 'Диабет 2 типа', confirmed: false },
      heightCm: 164,
      weightKg: 71,
      chronicConditions: ['Гипертония 1 ст.'],
      allergies: [],
      baselineUpdatedAt: '2026-04-08T09:35:00Z',
      identityVerifiedAt: '2026-04-08T09:36:00Z',
    },
    {
      // p4 — secondary demo patient with a critical-lab signature so the
      // critical-lab banner fires here without polluting the main flow on p2.
      id: 'p4',
      name: 'Волков Андрей Михайлович',
      dob: '1962-07-19',
      gender: 'male',
      phone: '+7 (916) 555-12-04',
      identifiers: { oms: '7700000000000004' },
      partnerClinic: 'endokor',
      department: 'Отделение диабетологии',
      attendingDoctorId: 'd1',
      createdAt: '2026-04-12T11:00:00Z',
      prepCompletedAt: '2026-04-26T20:05:00Z',
      prepTimeSpentMin: 11,
      diagnosis: { label: 'Диабет 2 типа, декомпенсация', confirmed: true },
      heightCm: 174,
      weightKg: 88,
      chronicConditions: ['Гипертония 3 ст.', 'ИБС'],
      allergies: ['Йод (контраст)'],
      baselineUpdatedAt: '2026-04-12T11:05:00Z',
      identityVerifiedAt: '2026-04-12T11:08:00Z',
    },
  ],

  accessGrants: [
    {
      id: 'ag-p2',
      patientId: 'p2',
      clinicId: 'endokor',
      scope: 'lifetime-clinic',
      grantedAt: '2026-04-05T10:01:00Z',
      department: 'Эндокринология',
      lastViewedAt: '2026-04-24T09:12:00Z',
    },
    {
      id: 'ag-p3',
      patientId: 'p3',
      clinicId: 'endokor',
      scope: 'lifetime-clinic',
      grantedAt: '2026-04-08T09:31:00Z',
      department: 'Эндокринология',
      lastViewedAt: '2026-04-22T15:48:00Z',
    },
    {
      id: 'ag-p4',
      patientId: 'p4',
      clinicId: 'endokor',
      scope: 'lifetime-clinic',
      grantedAt: '2026-04-12T11:01:00Z',
      department: 'Эндокринология',
      lastViewedAt: '2026-04-26T20:10:00Z',
    },
    // A02 access-audit set (20 masked grants; row 1 = p1 Мария, the rest
    // px* with no patient record). Read by the admin cockpit only.
    ...ACCESS_AUDIT_SEED,
  ],

  analyses: [
    {
      // Prior HbA1c uploaded by the patient as historical context — feeds the
      // «Динамика с прошлого визита» block on the doctor Обзор.
      id: 'an-p2-hba1c-prev',
      patientId: 'p2',
      type: 'HbA1c',
      label: 'Гликированный гемоглобин (HbA1c)',
      date: '2026-01-18',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: { HbA1c: '8.6 %', дата: '18.01.2026', норма: '< 6.5 %' },
      ocrFieldMeta: {
        HbA1c: {
          ref: '< 6.5 %',
          refMax: 6.5,
          numericValue: 8.6,
          unit: '%',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-05T10:28:00Z',
    },
    {
      // Prior Холестерин/ЛПНП uploaded as patient history — supports delta.
      id: 'an-p2-chol-prev',
      patientId: 'p2',
      type: 'cholesterol',
      label: 'Холестерин общий + ЛПНП',
      date: '2026-01-18',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Холестерин: '5.7 ммоль/л',
        ЛПНП: '3.4 ммоль/л',
        дата: '18.01.2026',
      },
      ocrFieldMeta: {
        Холестерин: {
          ref: '< 5.2 ммоль/л',
          refMax: 5.2,
          numericValue: 5.7,
          unit: 'ммоль/л',
        },
        ЛПНП: {
          ref: '< 3.0 ммоль/л',
          refMax: 3.0,
          numericValue: 3.4,
          unit: 'ммоль/л',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-05T10:29:00Z',
    },
    {
      id: 'an-p2-hba1c',
      patientId: 'p2',
      type: 'HbA1c',
      label: 'Гликированный гемоглобин (HbA1c)',
      date: '2026-03-22',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: { HbA1c: '7.8 %', дата: '22.03.2026', норма: '< 6.5 %' },
      ocrFieldMeta: {
        HbA1c: {
          ref: '< 6.5 %',
          refMax: 6.5,
          numericValue: 7.8,
          unit: '%',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-05T10:30:00Z',
    },
    {
      id: 'an-p2-glu',
      patientId: 'p2',
      type: 'glucose',
      label: 'Глюкоза крови натощак',
      date: '2026-03-22',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Глюкоза: '7.1 ммоль/л',
        дата: '22.03.2026',
        норма: '3.9–5.6 ммоль/л',
      },
      ocrFieldMeta: {
        Глюкоза: {
          ref: '3.9–5.6 ммоль/л',
          refMin: 3.9,
          refMax: 5.6,
          numericValue: 7.1,
          unit: 'ммоль/л',
          lowConfidence: true,
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-05T10:31:00Z',
    },
    {
      id: 'an-p2-creat',
      patientId: 'p2',
      type: 'creatinine',
      label: 'Креатинин сыворотки',
      date: '2026-03-22',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Креатинин: '88 мкмоль/л',
        дата: '22.03.2026',
        норма: '62–115 мкмоль/л',
      },
      ocrFieldMeta: {
        Креатинин: {
          ref: '62–115 мкмоль/л',
          refMin: 62,
          refMax: 115,
          numericValue: 88,
          unit: 'мкмоль/л',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-05T10:32:00Z',
    },
    {
      id: 'an-p2-chol',
      patientId: 'p2',
      type: 'cholesterol',
      label: 'Холестерин общий + ЛПНП',
      date: '2026-03-22',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Холестерин: '6.1 ммоль/л',
        ЛПНП: '3.8 ммоль/л',
        дата: '22.03.2026',
      },
      ocrFieldMeta: {
        Холестерин: {
          ref: '< 5.2 ммоль/л',
          refMax: 5.2,
          numericValue: 6.1,
          unit: 'ммоль/л',
        },
        ЛПНП: {
          ref: '< 3.0 ммоль/л',
          refMax: 3.0,
          numericValue: 3.8,
          unit: 'ммоль/л',
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-05T10:33:00Z',
    },
    {
      // p4 prior HbA1c — patient-uploaded history.
      id: 'an-p4-hba1c-prev',
      patientId: 'p4',
      type: 'HbA1c',
      label: 'Гликированный гемоглобин (HbA1c)',
      date: '2026-01-30',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: { HbA1c: '9.6 %', дата: '30.01.2026', норма: '< 6.5 %' },
      ocrFieldMeta: {
        HbA1c: {
          ref: '< 6.5 %',
          refMax: 6.5,
          numericValue: 9.6,
          unit: '%',
        },
      },
      status: 'acknowledged',
      uploadedAt: '2026-04-12T11:10:00Z',
    },
    {
      // p4 current HbA1c — critical, drives the critical-lab banner.
      id: 'an-p4-hba1c',
      patientId: 'p4',
      type: 'HbA1c',
      label: 'Гликированный гемоглобин (HbA1c)',
      date: '2026-04-18',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: { HbA1c: '11.4 %', дата: '18.04.2026', норма: '< 6.5 %' },
      ocrFieldMeta: {
        HbA1c: {
          ref: '< 6.5 %',
          refMax: 6.5,
          numericValue: 11.4,
          unit: '%',
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-26T19:40:00Z',
    },
    {
      // p4 fasting glucose — also at the critical threshold.
      id: 'an-p4-glu',
      patientId: 'p4',
      type: 'glucose',
      label: 'Глюкоза крови натощак',
      date: '2026-04-18',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Глюкоза: '14.2 ммоль/л',
        дата: '18.04.2026',
        норма: '3.9–5.6 ммоль/л',
      },
      ocrFieldMeta: {
        Глюкоза: {
          ref: '3.9–5.6 ммоль/л',
          refMin: 3.9,
          refMax: 5.6,
          numericValue: 14.2,
          unit: 'ммоль/л',
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-26T19:42:00Z',
    },
    {
      id: 'an-p3-chol',
      patientId: 'p3',
      type: 'cholesterol',
      label: 'Холестерин общий + ЛПНП',
      date: '2026-03-30',
      originalFileUrl: '',
      qualityCheck: 'clear',
      ocrFields: {
        Холестерин: '5.4 ммоль/л',
        ЛПНП: '3.6 ммоль/л',
        дата: '30.03.2026',
      },
      ocrFieldMeta: {
        Холестерин: {
          ref: '< 5.2 ммоль/л',
          refMax: 5.2,
          numericValue: 5.4,
          unit: 'ммоль/л',
        },
        ЛПНП: {
          ref: '< 3.0 ммоль/л',
          refMax: 3.0,
          numericValue: 3.6,
          unit: 'ммоль/л',
        },
      },
      status: 'uploaded',
      uploadedAt: '2026-04-08T11:00:00Z',
    },
  ],

  documents: [
    {
      id: 'doc-p2-passport',
      patientId: 'p2',
      type: 'passport',
      label: 'Паспорт',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-05T10:25:00Z',
      structureStatus: 'structured',
    },
    {
      id: 'doc-p2-oms',
      patientId: 'p2',
      type: 'oms',
      label: 'Полис ОМС',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-05T10:27:00Z',
      structureStatus: 'structured',
    },
    {
      id: 'doc-p2-referral',
      patientId: 'p2',
      type: 'referral',
      label: 'Направление от районной поликлиники',
      originalFileUrl: '',
      qualityCheck: 'acceptable',
      status: 'uploaded',
      uploadedAt: '2026-04-06T08:11:00Z',
      structureStatus: 'original-only',
      sourceFacility: 'Городская поликлиника',
      referralReason: 'Коррекция терапии СД 2 типа',
      referralDate: '2026-03-28',
    },
    {
      id: 'doc-p2-other-discharge',
      patientId: 'p2',
      type: 'other',
      label: 'Выписка после госпитализации, Городская больница (стационар)',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-07T16:34:00Z',
      structureStatus: 'original-only',
    },
    {
      id: 'doc-p4-passport',
      patientId: 'p4',
      type: 'passport',
      label: 'Паспорт',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-12T11:05:00Z',
      structureStatus: 'structured',
    },
    {
      id: 'doc-p4-oms',
      patientId: 'p4',
      type: 'oms',
      label: 'Полис ОМС',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-12T11:07:00Z',
      structureStatus: 'structured',
    },
    {
      id: 'doc-p3-passport',
      patientId: 'p3',
      type: 'passport',
      label: 'Паспорт',
      originalFileUrl: '',
      qualityCheck: 'clear',
      status: 'uploaded',
      uploadedAt: '2026-04-08T09:35:00Z',
      structureStatus: 'structured',
    },
    // ОМС намеренно не загружен: пациентка p3 показывает сценарий
    // «приём может задержаться на регистрации» и активирует JTBD
    // «Запросить через регистратуру» на D02 → Документы.
  ],
  complaints: [
    {
      id: 'cm-p2-1',
      patientId: 'p2',
      text: 'Утром цифры на глюкометре стабильно выше 8 — переживаю, что компенсация ушла.',
      createdAt: '2026-04-24T18:30:00Z',
      tags: ['glucose'],
      priority: 1,
    },
    {
      id: 'cm-p2-2',
      patientId: 'p2',
      text: 'К вечеру быстро устаю и отекают ноги — не понимаю, связано ли это с дозой.',
      createdAt: '2026-04-24T18:32:00Z',
      tags: ['energy'],
      priority: 2,
    },
    {
      id: 'cm-p2-3',
      patientId: 'p2',
      text: 'Хочу понять, нужно ли мне дополнительно сдавать что-то по почкам.',
      createdAt: '2026-04-25T19:15:00Z',
      tags: ['other'],
      priority: 3,
    },
    {
      id: 'cm-p2-4',
      patientId: 'p2',
      text: 'Иногда тяжело засыпать — думаю, это от тревоги перед визитом.',
      createdAt: '2026-04-25T19:18:00Z',
      tags: ['sleep'],
    },
    {
      id: 'cm-p4-1',
      patientId: 'p4',
      text: 'Сахар скачет, по утрам бывает за 13 ммоль/л — тяжело держать под контролем.',
      createdAt: '2026-04-26T19:55:00Z',
      tags: ['glucose'],
      priority: 1,
    },
    {
      id: 'cm-p4-2',
      patientId: 'p4',
      text: 'Пью воду чаще обычного и сильнее устаю к вечеру.',
      createdAt: '2026-04-26T19:57:00Z',
      tags: ['energy'],
      priority: 2,
    },
    {
      id: 'cm-p3-1',
      patientId: 'p3',
      text: 'Хочу обсудить, можно ли пересмотреть схему — устаю и набираю вес.',
      createdAt: '2026-04-21T20:10:00Z',
      tags: ['weight', 'energy'],
      priority: 1,
    },
    {
      id: 'cm-p3-2',
      patientId: 'p3',
      text: 'Беспокоят перепады настроения, особенно по вечерам.',
      createdAt: '2026-04-21T20:14:00Z',
      tags: ['mood'],
      priority: 2,
    },
  ],
  planItems: [
    {
      id: 'pi-p2-1',
      patientId: 'p2',
      requestId: 'req-p2-1',
      analysisType: 'HbA1c',
      label: 'HbA1c — повторный контроль',
      reason: 'Сравнить с показателем месячной давности.',
      status: 'uploaded',
      linkedAnalysisId: 'an-p2-hba1c',
      createdAt: '2026-04-15T08:00:00Z',
      dueDate: '2026-04-28',
    },
    {
      id: 'pi-p2-2',
      patientId: 'p2',
      requestId: 'req-p2-1',
      analysisType: 'creatinine',
      label: 'Креатинин + СКФ',
      reason: 'Базовая оценка функции почек.',
      status: 'acknowledged',
      linkedAnalysisId: 'an-p2-creat',
      createdAt: '2026-04-15T08:00:00Z',
      dueDate: '2026-04-28',
    },
    {
      id: 'pi-p2-3',
      patientId: 'p2',
      requestId: 'req-p2-1',
      analysisType: 'other',
      label: 'Микроальбумин в моче',
      reason: 'Скрининг диабетической нефропатии.',
      status: 'assigned',
      createdAt: '2026-04-15T08:00:00Z',
      dueDate: '2026-04-28',
    },
  ],
  doctorRequests: [
    {
      id: 'req-p2-1',
      patientId: 'p2',
      fromDoctorId: 'd1',
      title: 'Подготовка к плановому приёму',
      body: 'Сдайте, пожалуйста, перечисленные анализы за неделю до визита.',
      planItemIds: ['pi-p2-1', 'pi-p2-2', 'pi-p2-3'],
      createdAt: '2026-04-15T08:00:00Z',
      seenByPatient: true,
      intent: 'before-visit',
    },
  ],
  appointments: [
    {
      id: 'apt-p2-main',
      patientId: 'p2',
      doctorId: 'd1',
      type: 'main',
      date: '2026-05-04T10:00:00Z',
      status: 'scheduled',
      createdAt: '2026-04-05T10:02:00Z',
    },
    // Past completed visits for Мария — let the doctor compare against a
    // specific historical appointment in the «Динамика» block. Other demo
    // patients have no completed visits, which trips the first-visit notice.
    {
      id: 'apt-p2-prev-1',
      patientId: 'p2',
      doctorId: 'd1',
      type: 'main',
      date: '2026-01-22T10:00:00Z',
      status: 'completed',
      createdAt: '2025-12-15T09:00:00Z',
    },
    {
      id: 'apt-p2-prev-2',
      patientId: 'p2',
      doctorId: 'd1',
      type: 'main',
      date: '2025-10-15T10:00:00Z',
      status: 'completed',
      createdAt: '2025-09-20T09:00:00Z',
    },
    {
      id: 'apt-p4-main',
      patientId: 'p4',
      doctorId: 'd1',
      type: 'main',
      date: '2026-05-04T11:00:00Z',
      status: 'scheduled',
      createdAt: '2026-04-12T11:02:00Z',
    },
    {
      id: 'apt-p3-main',
      patientId: 'p3',
      doctorId: 'd1',
      type: 'main',
      date: '2026-05-06T11:30:00Z',
      status: 'scheduled',
      createdAt: '2026-04-08T09:32:00Z',
    },
  ],

  // ─── Admin slices (aggregate, no PII) ──────────────────────────────────────
  pilotKpis: PILOT_KPIS_SEED,
  pilotGoal: PILOT_GOAL_SEED,
  funnel: FUNNEL_SEED,
  adoptionByDepartment: ADOPTION_BY_DEPARTMENT_SEED,
  adoptionByDoctor: ADOPTION_BY_DOCTOR_SEED,
  kpiTrend: KPI_TREND_SEED,
  accessByDepartment: ACCESS_BY_DEPARTMENT_SEED,
  accessIncidents: ACCESS_INCIDENTS_SEED,
  auditEvents: AUDIT_EVENTS_SEED,
  complianceState: COMPLIANCE_STATE_SEED,
  complianceChecks: COMPLIANCE_CHECKS_SEED,
}
