import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

// PWA shell — installable PATIENT surface only (gating lives in app code,
// see src/pwa/InstallPrompt.tsx). No Web Push / VAPID here by design.
//
// registerType 'autoUpdate' + skipWaiting + clientsClaim => a new build takes
// over immediately on next load, so the demo never gets pinned to a stale SW.
// Data calls (backend API, Anthropic) are NetworkFirst/NetworkOnly — never
// CacheFirst — so an installed shell can't serve stale clinical data.
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: 'auto',
      // Build-time icons live in public/ (generated by scripts/generate-pwa-icons.mjs).
      includeAssets: [
        'apple-touch-icon-180x180.png',
        'pwa-192x192.png',
        'pwa-512x512.png',
        'maskable-512x512.png',
      ],
      manifest: {
        name: 'IntelDoc — Эндокор',
        short_name: 'IntelDoc',
        description: 'Подготовка к приёму и доступ к анализам',
        lang: 'ru',
        // start_url is the patient home, NOT '/' (which redirects to onboarding).
        start_url: '/patient/home',
        // scope keeps the installed app inside the patient surface.
        scope: '/patient/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#0B1B3B',
        theme_color: '#0B1B3B',
        icons: [
          {
            src: '/pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/maskable-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Take over immediately so the demo is never stuck on an old build.
        skipWaiting: true,
        clientsClaim: true,
        // SPA fallback so deep links resolve to the app shell.
        navigateFallback: '/index.html',
        // Precache the hashed build output via the auto-generated manifest.
        // Do NOT hand-list hashed files here.
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],
        runtimeCaching: [
          // Google Fonts stylesheet — refreshable, safe to serve stale briefly.
          {
            urlPattern: ({ url }) => url.origin === 'https://fonts.googleapis.com',
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'google-fonts-stylesheets',
            },
          },
          // Google Fonts files — long-lived, cacheable.
          {
            urlPattern: ({ url }) => url.origin === 'https://fonts.gstatic.com',
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'google-fonts-webfonts',
              expiration: {
                maxEntries: 30,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
              },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          // Anthropic API (in-browser Vasily chat) — never cache model calls.
          {
            urlPattern: ({ url }) => url.hostname.endsWith('anthropic.com'),
            handler: 'NetworkOnly',
          },
          // Backend / data calls — always go to the network first; never serve
          // stale clinical data from cache. Covers the /v1 API, the dev
          // api-check, and any localhost/api host the prototype talks to.
          {
            urlPattern: ({ url, sameOrigin }) =>
              url.pathname.startsWith('/v1') ||
              url.pathname.startsWith('/dev/api-check') ||
              (!sameOrigin && /\/(api|v1)\//.test(url.pathname)),
            handler: 'NetworkFirst',
            options: {
              cacheName: 'inteldoc-api',
              networkTimeoutSeconds: 10,
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      devOptions: {
        // Keep the SW out of `vite dev` so normal-tab dev behavior is unchanged.
        enabled: false,
      },
    }),
  ],
  server: {
    host: true,
    allowedHosts: ['.trycloudflare.com'],
  },
})
